// Package generator 提供代码生成器。
// 从 .api DSL 的 AST 自动生成：
//   - Go 类型定义（DTO）
//   - HTTP Handler 框架代码
//   - gRPC Service 框架代码
//   - 客户端 SDK
//   - OpenAPI v3 文档
//   - Protobuf 定义文件
package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/xyxuliang/nexus-micro/dsl/ast"
	"github.com/xyxuliang/nexus-micro/dsl/parser"
	"github.com/xyxuliang/nexus-micro/internal/util"
)

// Generator 是代码生成器。
type Generator struct {
	outputDir string // 输出目录
	module    string // Go module 路径
}

// New 创建一个新的代码生成器。
func New(outputDir, module string) *Generator {
	return &Generator{
		outputDir: outputDir,
		module:    module,
	}
}

// GenerateFromFile 从 .api 文件生成代码。
func (g *Generator) GenerateFromFile(apiFile string) error {
	content, err := os.ReadFile(apiFile)
	if err != nil {
		return fmt.Errorf("generator: cannot read file %s: %w", apiFile, err)
	}

	return g.Generate(string(content))
}

// Generate 从 DSL 源码生成代码。
func (g *Generator) Generate(source string) error {
	// 1. 解析 DSL → AST
	p := parser.New(source)
	file, errs := p.Parse()
	if len(errs) > 0 {
		for _, err := range errs {
			fmt.Fprintf(os.Stderr, "parse error: %v\n", err)
		}
		return fmt.Errorf("generator: %d parse errors", len(errs))
	}

	// 2. 确保输出目录存在
	if err := g.ensureOutputDir(); err != nil {
		return err
	}

	// 3. 生成代码
	for _, svc := range file.Services {
		svcDir := filepath.Join(g.outputDir, svc.Group)
		internalDir := filepath.Join(svcDir, "internal")

		// 3.1 生成 config 目录
		configDir := filepath.Join(internalDir, "config")
		os.MkdirAll(configDir, 0755)
		g.generateConfig(configDir, svc, file)

		// 3.2 生成 handler 目录
		handlerDir := filepath.Join(internalDir, "handler")
		os.MkdirAll(handlerDir, 0755)
		g.generateHandlers(handlerDir, svc, file)

		// 3.3 生成 logic 目录
		logicDir := filepath.Join(internalDir, "logic")
		os.MkdirAll(logicDir, 0755)
		g.generateLogic(logicDir, svc)

		// 3.4 生成 svc 目录
		svcCtxDir := filepath.Join(internalDir, "svc")
		os.MkdirAll(svcCtxDir, 0755)
		g.generateServiceContext(svcCtxDir, svc)

		// 3.5 生成 middleware 目录
		middlewareDir := filepath.Join(internalDir, "middleware")
		os.MkdirAll(middlewareDir, 0755)
		g.generateMiddleware(middlewareDir, svc)

		// 3.6 生成 client 目录
		clientDir := filepath.Join(svcDir, "client")
		os.MkdirAll(clientDir, 0755)
		g.generateClient(clientDir, svc)

		// 3.7 生成 docs 目录
		docsDir := filepath.Join(svcDir, "docs")
		os.MkdirAll(docsDir, 0755)
		g.generateOpenAPI(docsDir, svc, file)

		// 3.8 生成 server 目录
		serverDir := filepath.Join(internalDir, "server")
		os.MkdirAll(serverDir, 0755)
		g.generateServer(serverDir, svc)

		// 3.9 生成 main.go
		g.generateMain(svcDir, svc)

		// 3.10 生成 proto 文件
		g.generateProto(svcDir, svc, file)
	}

	return nil
}

// ensureOutputDir 确保输出目录存在。
func (g *Generator) ensureOutputDir() error {
	return os.MkdirAll(g.outputDir, 0755)
}

// generateConfig 生成配置结构体。
func (g *Generator) generateConfig(dir string, svc *ast.Service, file *ast.File) {
	content := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// Package config 提供 %s 服务的配置结构体。
package config

import (
	"github.com/xyxuliang/nexus-micro/core/config"
)

// Config 是 %s 服务的配置结构体。
type Config struct {
	ServiceName string
	HttpPort    int
	GrpcPort    int
}

// NewConfig 创建默认配置。
func NewConfig(cfg *config.Config) *Config {
	return &Config{
		ServiceName: cfg.GetString("server.name"),
		HttpPort:    cfg.GetInt("server.http.port"),
		GrpcPort:    cfg.GetInt("server.grpc.port"),
	}
}
`, svc.Name, svc.Name)

	os.WriteFile(filepath.Join(dir, "config.go"), []byte(content), 0644)
}

// generateHandlers 生成 HTTP + gRPC Handler 框架代码。
func (g *Generator) generateHandlers(dir string, svc *ast.Service, file *ast.File) {
	for _, handler := range svc.Handlers {
		handlerName := toSnakeCase(handler.Name)
		content := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// Handler: %s — %s
package handler

import (
	"context"

	"github.com/xyxuliang/nexus-micro/core"
	"github.com/xyxuliang/nexus-micro/core/response"
	"%s/service/%s/internal/logic"
	"%s/service/%s/internal/svc"
)

// %sHandler 是 %s 的处理函数。
// HTTP 和 gRPC 请求共享此处理函数。
func %sHandler(ctx context.Context, svcCtx *svc.ServiceContext, req interface{}) (interface{}, error) {
	// TODO: 解析请求参数
	logic := logic.New%sLogic(ctx, svcCtx)
	return logic.Execute()
}
`, handler.Name, handler.Doc, g.module, svc.Group, g.module, svc.Group, handler.Name, handler.Doc, handler.Name, handler.Name)

		os.WriteFile(filepath.Join(dir, handlerName+".go"), []byte(content), 0644)
	}
}

// generateLogic 生成业务逻辑框架代码。
func (g *Generator) generateLogic(dir string, svc *ast.Service) {
	for _, handler := range svc.Handlers {
		handlerName := toSnakeCase(handler.Name)
		content := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// Logic: %s
// 在此文件中实现具体的业务逻辑。
package logic

import (
	"context"

	"%s/service/%s/internal/svc"
)

// %sLogic 是 %s 的业务逻辑。
type %sLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

// New%sLogic 创建业务逻辑实例。
func New%sLogic(ctx context.Context, svcCtx *svc.ServiceContext) *%sLogic {
	return &%sLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Execute 执行业务逻辑。
func (l *%sLogic) Execute() (interface{}, error) {
	// TODO: 实现业务逻辑
	return nil, nil
}
`, handler.Doc, g.module, svc.Group, handler.Name, handler.Doc, handler.Name, handler.Name, handler.Name, handler.Name, handler.Name)

		os.WriteFile(filepath.Join(dir, handlerName+".go"), []byte(content), 0644)
	}
}

// generateServiceContext 生成服务上下文（依赖注入容器）。
func (g *Generator) generateServiceContext(dir string, svc *ast.Service) {
	content := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// Package svc 提供 %s 服务的依赖注入上下文。
package svc

import (
	"%s/service/%s/internal/config"
)

// ServiceContext 是 %s 服务的依赖注入上下文。
// 所有需要注入的依赖项都定义在此结构体中。
type ServiceContext struct {
	Config *config.Config
}

// NewServiceContext 创建服务上下文。
func NewServiceContext(cfg *config.Config) *ServiceContext {
	return &ServiceContext{
		Config: cfg,
	}
}
`, svc.Name, g.module, svc.Group, svc.Name)

	os.WriteFile(filepath.Join(dir, "service_context.go"), []byte(content), 0644)
}

// generateMiddleware 生成中间件代码。
func (g *Generator) generateMiddleware(dir string, svc *ast.Service) {
	content := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// Package middleware 提供 %s 服务的自定义中间件。
package middleware

import (
	"context"

	"github.com/xyxuliang/nexus-micro/core"
)

// AuthMiddleware 是示例认证中间件。
// 在此实现自定义的认证逻辑。
func AuthMiddleware() core.Middleware {
	return func(next core.Handler) core.Handler {
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			// TODO: 实现认证逻辑
			return next(ctx, req)
		}
	}
}
`, svc.Name)

	os.WriteFile(filepath.Join(dir, "auth.go"), []byte(content), 0644)
}

// generateClient 生成客户端 SDK。
func (g *Generator) generateClient(dir string, svc *ast.Service) {
	var methods strings.Builder
	for _, handler := range svc.Handlers {
		methods.WriteString(fmt.Sprintf(`// %s 调用 %s 接口。
func (c *Client) %s(ctx context.Context, req interface{}) (interface{}, error) {
	// TODO: 实现 RPC 调用
	return c.call(ctx, "%s", req)
}
`, handler.Name, handler.Doc, handler.Name, handler.Name))
	}

	content := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// Package client 提供 %s 服务的 HTTP 客户端 SDK。
package client

import (
	"context"
)

// Client 是 %s 服务的客户端。
type Client struct {
	serviceName string
	httpAddr    string
}

// NewClient 创建客户端实例。
func NewClient(httpAddr string) *Client {
	return &Client{
		serviceName: "%s",
		httpAddr:    httpAddr,
	}
}

// call 执行 RPC 调用。
func (c *Client) call(ctx context.Context, method string, req interface{}) (interface{}, error) {
	// TODO: 实现 HTTP/gRPC 调用
	return nil, nil
}

%s
`, svc.Name, svc.Name, svc.Group, methods.String())

	os.WriteFile(filepath.Join(dir, "http_client.go"), []byte(content), 0644)
}

// generateOpenAPI 生成 OpenAPI v3 文档。
func (g *Generator) generateOpenAPI(dir string, svc *ast.Service, file *ast.File) {
	content := fmt.Sprintf(`# OpenAPI v3.0 — %s
# Generated by Nexus Micro

openapi: "3.0.0"
info:
  title: %s
  description: %s
  version: %s
servers:
  - url: %s
paths:
`, svc.Name, svc.Name, file.Info.Desc, file.Info.Version, svc.Prefix)

	for _, handler := range svc.Handlers {
		content += fmt.Sprintf(`  %s:
    %s:
      summary: %s
      operationId: %s
      responses:
        "200":
          description: OK
`,
			handler.Path, strings.ToLower(handler.Method), handler.Doc, handler.Name)
	}

	os.WriteFile(filepath.Join(dir, "openapi.yaml"), []byte(content), 0644)
}

// generateServer 生成 HTTP/gRPC 服务器代码。
func (g *Generator) generateServer(dir string, svc *ast.Service) {
	httpContent := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// HTTP 服务器路由注册。
package server

import (
	"net/http"

	"github.com/xyxuliang/nexus-micro/core"
	"%s/service/%s/internal/handler"
	"%s/service/%s/internal/svc"
)

// RegisterHTTPRoutes 注册 HTTP 路由。
func RegisterHTTPRoutes(mux *http.ServeMux, svcCtx *svc.ServiceContext) {
`, g.module, svc.Group, g.module, svc.Group)

	for _, handler := range svc.Handlers {
		httpContent += fmt.Sprintf(`	// %s: %s
	mux.HandleFunc("%s%s", func(w http.ResponseWriter, r *http.Request) {
		handler.%sHandler(r.Context(), svcCtx, nil)
	})
`, handler.Name, handler.Doc, svc.Prefix, handler.Path, handler.Name)
	}

	httpContent += "}\n"
	os.WriteFile(filepath.Join(dir, "http.go"), []byte(httpContent), 0644)

	grpcContent := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// gRPC 服务器路由注册。
package server

// RegisterGRPCRoutes 注册 gRPC 路由（预留）。
func RegisterGRPCRoutes() {
	// TODO: 实现 gRPC 服务注册
}
`)
	os.WriteFile(filepath.Join(dir, "grpc.go"), []byte(grpcContent), 0644)
}

// generateMain 生成 main.go 入口文件。
func (g *Generator) generateMain(dir string, svc *ast.Service) {
	content := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// %s 服务入口。
package main

import (
	"github.com/xyxuliang/nexus-micro/core/server"
	"%s/service/%s/internal/config"
	"%s/service/%s/internal/svc"
)

func main() {
	srv := server.New(
		server.WithName("%s"),
		server.WithConfig("etc/%s.yaml"),
	)

	// 初始化服务上下文
	cfg := config.NewConfig(srv.Config())
	svcCtx := svc.NewServiceContext(cfg)

	// 注册业务服务
	_ = svcCtx

	// 启动服务
	srv.Start()
}
`, svc.Name, g.module, svc.Group, g.module, svc.Group, svc.Group, svc.Group)

	os.WriteFile(filepath.Join(dir, "main.go"), []byte(content), 0644)
}

// generateProto 生成 Protobuf 定义文件。
func (g *Generator) generateProto(dir string, svc *ast.Service, file *ast.File) {
	content := fmt.Sprintf(`// %s.proto — Generated by Nexus Micro
syntax = "proto3";

package %s;

option go_package = "%s/service/%s";

service %s {
`, svc.Group, svc.Group, g.module, svc.Group, svc.Name)

	for _, handler := range svc.Handlers {
		if handler.HasGRPC {
			content += fmt.Sprintf(`  rpc %s(%sReq) returns (%sResp);
`, handler.Name, handler.Name, handler.Name)
		}
	}

	content += "}\n\n"

	// 生成消息定义
	for _, t := range file.Types {
		content += fmt.Sprintf("message %s {\n", t.Name)
		for i, field := range t.Fields {
			protoType := goTypeToProto(field.Type)
			content += fmt.Sprintf("  %s %s = %d;\n", protoType, strings.ToLower(field.Name), i+1)
		}
		content += "}\n\n"
	}

	os.WriteFile(filepath.Join(dir, svc.Group+".proto"), []byte(content), 0644)
}

// toSnakeCase 将 PascalCase 转换为 snake_case（委托给 util 包）。
func toSnakeCase(s string) string {
	return util.ToSnakeCase(s)
}

// goTypeToProto 将 Go 类型转换为 Proto 类型（委托给 util 包）。
func goTypeToProto(goType string) string {
	return util.GoTypeToProto(goType)
}
