// Package generator 提供代码生成器。
// 从 .api DSL 的 AST 自动生成：
//   - Go 类型定义（DTO）
//   - HTTP Handler 框架代码（含完整中间件链和路由注册）
//   - gRPC Service 框架代码
//   - 客户端 SDK
//   - OpenAPI v3 文档
//   - Protobuf 定义文件
package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/xyxuliang/nexus-micro/dsl/ast"
	"github.com/xyxuliang/nexus-micro/dsl/parser"
)

// Generator 是代码生成器。
type Generator struct {
	outputDir string // 输出目录
	module    string // Go module 路径
}

// New 创建一个新的代码生成器。
// outputDir: 输出目录名（如 "service"、"client"）
// module: Go module 路径（如 "github.com/xyxuliang/nexus-micro"）
func New(outputDir, module string) *Generator {
	return &Generator{
		outputDir: outputDir,
		module:    module,
	}
}

// GenerateFromFile 从 .api 文件生成代码。
// 包含完整的解析 → 校验 → 生成流程。
func (g *Generator) GenerateFromFile(apiFile string) error {
	content, err := os.ReadFile(apiFile)
	if err != nil {
		return fmt.Errorf("generator: cannot read file %s: %w", apiFile, err)
	}
	return g.Generate(string(content))
}

// Generate 从 DSL 源码生成代码。
// 流程：解析 DSL → 生成 config → handler → logic → svc → middleware → client → docs → server → main → proto。
func (g *Generator) Generate(source string) error {
	// 1. 解析 DSL → AST
	p := parser.New(source)
	file, errs := p.Parse()
	if len(errs) > 0 {
		for _, err := range errs {
			fmt.Fprintf(os.Stderr, "parse error: %v\n", err)
		}
		return fmt.Errorf("generator: %d parse errors", len(errs))
	}

	// 2. 确保输出目录存在
	if err := g.ensureOutputDir(); err != nil {
		return err
	}

	// 3. 为每个 service 生成代码
	for _, svc := range file.Services {
		svcDir := filepath.Join(g.outputDir, svc.Group)
		internalDir := filepath.Join(svcDir, "internal")

		// 3.1 生成 dto 目录（数据传输对象）
		dtoDir := filepath.Join(internalDir, "dto")
		os.MkdirAll(dtoDir, 0755)
		g.generateDTO(dtoDir, svc, file)

		// 3.2 生成 config 目录
		configDir := filepath.Join(internalDir, "config")
		os.MkdirAll(configDir, 0755)
		g.generateConfig(configDir, svc, file)

		// 3.3 生成 handler 目录
		handlerDir := filepath.Join(internalDir, "handler")
		os.MkdirAll(handlerDir, 0755)
		g.generateHandlers(handlerDir, svc, file)

		// 3.4 生成 logic 目录
		logicDir := filepath.Join(internalDir, "logic")
		os.MkdirAll(logicDir, 0755)
		g.generateLogic(logicDir, svc)

		// 3.5 生成 svc 目录
		svcCtxDir := filepath.Join(internalDir, "svc")
		os.MkdirAll(svcCtxDir, 0755)
		g.generateServiceContext(svcCtxDir, svc)

		// 3.6 生成 router 目录
		routerDir := filepath.Join(internalDir, "router")
		os.MkdirAll(routerDir, 0755)
		g.generateRouter(routerDir, svc, file)

		// 3.7 生成 middleware 目录
		middlewareDir := filepath.Join(internalDir, "middleware")
		os.MkdirAll(middlewareDir, 0755)
		g.generateMiddleware(middlewareDir, svc)

		// 3.8 生成 client 目录
		clientDir := filepath.Join(svcDir, "client")
		os.MkdirAll(clientDir, 0755)
		g.generateClient(clientDir, svc)

		// 3.9 生成 docs 目录
		docsDir := filepath.Join(svcDir, "docs")
		os.MkdirAll(docsDir, 0755)
		g.generateOpenAPI(docsDir, svc, file)

		// 3.10 生成 main.go
		g.generateMain(svcDir, svc, file)

		// 3.11 生成 proto 文件
		g.generateProto(svcDir, svc, file)

		// 3.12 生成默认 YAML 配置文件
		g.generateServiceYAML(svcDir, svc)
	}

	return nil
}

// ensureOutputDir 确保输出目录存在。
func (g *Generator) ensureOutputDir() error {
	return os.MkdirAll(g.outputDir, 0755)
}

// =============================================================================
// DTO 生成
// =============================================================================

// generateDTO 生成数据传输对象（DTO）。
// 从 DSL type 定义生成 Go 结构体，每个类型一个文件。
func (g *Generator) generateDTO(dir string, svc *ast.Service, file *ast.File) {
	for _, t := range file.Types {
		name := toSnakeCase(t.Name)

		var fields strings.Builder
		for _, f := range t.Fields {
			tag := fmt.Sprintf(`json:"%s"`, toSnakeCase(f.Name))
			fields.WriteString(fmt.Sprintf("\t%s %s `%s`\n", f.Name, goTypeToGo(f.Type), tag))
		}

		content := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
package dto

// %s %s
type %s struct {
%s}
`, t.Name, t.Doc, t.Name, fields.String())

		os.WriteFile(filepath.Join(dir, name+".go"), []byte(content), 0644)
	}
}

// =============================================================================
// Router 生成
// =============================================================================

// generateRouter 生成路由注册文件。
// 使用 Gin 路由引擎，每个 handler 独立注册。
func (g *Generator) generateRouter(dir string, svc *ast.Service, file *ast.File) {
	var registrations strings.Builder
	for _, handler := range svc.Handlers {
		registrations.WriteString(fmt.Sprintf(
			`	// %s: %s %s%s
	api.%s("%s", h.%s(svcCtx))
`,
			handler.Doc, handler.Method, svc.Prefix, handler.Path,
			strings.ToUpper(handler.Method), handler.Path, handler.Name))
	}

	content := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// Package router 提供 HTTP 路由注册。
package router

import (
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"%s/core/middleware"
	"%s/service/%s/internal/handler"
	"%s/service/%s/internal/svc"
)

// Register 注册所有路由到 Gin 引擎。
func Register(r *gin.Engine, svcCtx *svc.ServiceContext) {
	h := handler.NewHandler()

	// 健康检查
	r.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"code":    0,
			"message": "ok",
			"data": gin.H{
				"service": svcCtx.Config.Server.Name,
				"status":  "healthy",
				"version": "%s",
				"time":    time.Now().Format(time.RFC3339),
			},
		})
	})

	// 业务路由
	api := r.Group("%s")
	{
%s	}
}
`, g.module, g.module, svc.Group, g.module, svc.Group,
		file.Info.Version, svc.Prefix, registrations.String())

	os.WriteFile(filepath.Join(dir, "router.go"), []byte(content), 0644)
}

// goTypeToGo 将 .api 类型转为 Go 类型。
func goTypeToGo(apiType string) string {
	if strings.HasPrefix(apiType, "[]") {
		return "[]" + goTypeToGo(apiType[2:])
	}
	switch apiType {
	case "string":
		return "string"
	case "int", "int32":
		return "int32"
	case "int64":
		return "int64"
	case "float", "float64":
		return "float64"
	case "bool":
		return "bool"
	default:
		return apiType
	}
}

// =============================================================================
// 配置生成
// =============================================================================

// generateConfig 生成服务配置结构体。
// 包含服务器配置、治理组件配置、中间件配置和注册中心配置。
func (g *Generator) generateConfig(dir string, svc *ast.Service, file *ast.File) {
	content := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// Package config 提供 %s 服务的配置结构体。
//
// 配置从 etc/%s.yaml 加载，所有字段都有合理的默认值。
// 支持 YAML 格式，可通过环境变量覆盖关键配置。
package config

import (
	"time"

	"%s/core/config"
)

// =============================================================================
// Config — %s 服务配置
// =============================================================================
// 对应 etc/%s.yaml 的 YAML 结构体。
// 使用 config.New() 加载配置文件，自动填充默认值。

// Config 是 %s 服务的完整配置。
type Config struct {
	Server    ServerConfig    `+"`yaml:\"server\"`"+`
	Governance GovernanceConfig `+"`yaml:\"governance\"`"+`
	Middleware MiddlewareConfig `+"`yaml:\"middleware\"`"+`
	Registry   RegistryConfig   `+"`yaml:\"registry\"`"+`
	Log        LogConfig        `+"`yaml:\"log\"`"+`
}

// ServerConfig 是 HTTP/gRPC 服务器配置。
type ServerConfig struct {
	Name string    `+"`yaml:\"name\"`"+`
	HTTP HTTPConfig `+"`yaml:\"http\"`"+`
	GRPC GRPCConfig `+"`yaml:\"grpc\"`"+`
}

// HTTPConfig 是 HTTP 服务器配置。
type HTTPConfig struct {
	Port int `+"`yaml:\"port\"`"+`
}

// GRPCConfig 是 gRPC 服务器配置。
type GRPCConfig struct {
	Port int `+"`yaml:\"port\"`"+`
}

// GovernanceConfig 是服务治理组件配置。
// 包含限流、熔断、降级和超时配置。
type GovernanceConfig struct {
	RateLimit      RateLimitConfig      `+"`yaml:\"ratelimit\"`"+`
	CircuitBreaker CircuitBreakerConfig `+"`yaml:\"circuitbreaker\"`"+`
	Shedding       SheddingConfig       `+"`yaml:\"shedding\"`"+`
	Timeout        time.Duration        `+"`yaml:\"timeout\"`"+`
}

// RateLimitConfig 是限流配置（令牌桶算法）。
type RateLimitConfig struct {
	Rate  int `+"`yaml:\"rate\"`"+`  // 每秒请求数
	Burst int `+"`yaml:\"burst\"`"+` // 突发请求数
}

// CircuitBreakerConfig 是熔断配置（三态自适应）。
type CircuitBreakerConfig struct {
	WindowSize  string  `+"`yaml:\"window_size\"`"+`
	BucketCount int     `+"`yaml:\"bucket_count\"`"+`
	MinRequests int     `+"`yaml:\"min_requests\"`"+`
	ErrorRate   float64 `+"`yaml:\"error_rate\"`"+`
	SleepWindow string  `+"`yaml:\"sleep_window\"`"+`
}

// SheddingConfig 是降级配置（CPU+内存双层保护）。
type SheddingConfig struct {
	CPUThreshold float64 `+"`yaml:\"cpu_threshold\"`"+`
	MemThreshold float64 `+"`yaml:\"mem_threshold\"`"+`
}

// MiddlewareConfig 是中间件配置。
type MiddlewareConfig struct {
	CORS      bool `+"`yaml:\"cors\"`"+`
	RequestID bool `+"`yaml:\"request_id\"`"+`
	Tracing   bool `+"`yaml:\"tracing\"`"+`
	Logger    bool `+"`yaml:\"logger\"`"+`
	Recovery  bool `+"`yaml:\"recovery\"`"+`
	Metrics   bool `+"`yaml:\"metrics\"`"+`
}

// RegistryConfig 是注册中心配置。
type RegistryConfig struct {
	Provider        string   `+"`yaml:\"provider\"`"+`
	StaticEndpoints []string `+"`yaml:\"static_endpoints\"`"+`
	EtcdEndpoints   []string `+"`yaml:\"etcd_endpoints\"`"+`
	ConsulAddr      string   `+"`yaml:\"consul_addr\"`"+`
}

// LogConfig 是日志配置。
type LogConfig struct {
	Level  string `+"`yaml:\"level\"`"+`  // debug | info | warn | error
	Format string `+"`yaml:\"format\"`"+` // json | text
}

// =============================================================================
// NewConfig — 工厂方法
// =============================================================================

// NewConfig 从框架配置创建服务配置。
// 自动从 config.Config 中提取各字段并填充默认值。
func NewConfig(cfg *config.Config) *Config {
	c := &Config{
		Server: ServerConfig{
			Name: cfg.GetString("server.name"),
			HTTP: HTTPConfig{
				Port: cfg.GetInt("server.http.port"),
			},
			GRPC: GRPCConfig{
				Port: cfg.GetInt("server.grpc.port"),
			},
		},
		Governance: GovernanceConfig{
			RateLimit: RateLimitConfig{
				Rate:  cfg.GetInt("ratelimit.rate"),
				Burst: cfg.GetInt("ratelimit.burst"),
			},
			CircuitBreaker: CircuitBreakerConfig{
				WindowSize:  cfg.GetString("circuitbreaker.window_size"),
				BucketCount: cfg.GetInt("circuitbreaker.bucket_count"),
				MinRequests: cfg.GetInt("circuitbreaker.min_requests"),
				ErrorRate:   cfg.GetFloat("circuitbreaker.error_rate"),
				SleepWindow: cfg.GetString("circuitbreaker.sleep_window"),
			},
			Shedding: SheddingConfig{
				CPUThreshold: cfg.GetFloat("shedding.cpu_threshold"),
				MemThreshold: cfg.GetFloat("shedding.mem_threshold"),
			},
			Timeout: cfg.GetDuration("server.timeout"),
		},
		Middleware: MiddlewareConfig{
			RequestID: true,
			Tracing:   true,
			Logger:    true,
			Recovery:  true,
			CORS:      true,
			Metrics:   true,
		},
		Registry: RegistryConfig{
			Provider: cfg.GetString("discovery.provider"),
		},
		Log: LogConfig{
			Level:  cfg.GetString("log.level"),
			Format: cfg.GetString("log.format"),
		},
	}

	return c
}
`, svc.Name, svc.Group, g.module, svc.Name, svc.Group, svc.Name)

	os.WriteFile(filepath.Join(dir, "config.go"), []byte(content), 0644)
}

// =============================================================================
// Handler 生成
// =============================================================================

// generateHandlers 生成 HTTP + gRPC Handler 框架代码。
// 每个 handler 生成一个独立文件，包含请求解析和响应封装。
// 同时生成 routes.go 用于集中注册所有路由。
// SSE 端点 (IsSSE=true) 生成 Channel-based SSE handler，自动绕过 JSON 包装。
func (g *Generator) generateHandlers(dir string, svc *ast.Service, file *ast.File) {
	for _, handler := range svc.Handlers {
		handlerName := toSnakeCase(handler.Name)

		if handler.IsSSE {
			// SSE 端点：生成 Channel-based SSE handler
			content := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// SSE Handler: %s — %s
// 此文件由 nx gen api 自动生成，请勿手动编辑。
//
// 使用 Server-Sent Events 协议实现实时数据推送。
// 客户端通过 EventSource API 连接，无需轮询。
package handler

import (
	"context"
	"fmt"
	"time"

	"%s/core/sse"
	"%s/service/%s/internal/logic"
	"%s/service/%s/internal/svc"
)

// %sSSEHandler 创建 %s 的 SSE 事件处理器。
// 返回一个 http.Handler，自动管理连接、心跳和事件推送。
//
// 客户端连接方式：
//   const es = new EventSource("/sse/%s");
//   es.addEventListener("message", (e) => { console.log(e.data); });
//   es.addEventListener("error", () => { es.close(); });
func %sSSEHandler(svcCtx *svc.ServiceContext) http.Handler {
	return sse.NewChannelHandler(func(ch chan<- sse.Event, r *http.Request) {
		// 提取 Last-Event-ID（断线重连）
		lastID := sse.ParseLastEventID(r)
		_ = lastID

		ctx := r.Context()
		l := logic.New%sSSELogic(ctx, svcCtx)

		// 调用业务逻辑获取事件流
		eventCh := l.Execute()
		for {
			select {
			case evt, ok := <-eventCh:
				if !ok {
					return
				}
				select {
				case ch <- evt:
				case <-ctx.Done():
					return
				}
			case <-ctx.Done():
				return
			}
		}
	}, &sse.ChannelConfig{
		HeartbeatInterval: 30 * time.Second,
		BufferSize:        64,
	})
}
`, handler.Name, handler.Doc, g.module, g.module, svc.Group, g.module, svc.Group,
				handler.Name, handler.Doc, handler.Path, handler.Name, handler.Name)

			os.WriteFile(filepath.Join(dir, handlerName+"_sse.go"), []byte(content), 0644)
		} else {
			// 标准 Handler
			content := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// Handler: %s — %s
// 此文件由 nx gen api 自动生成，请勿手动编辑。
//
// gRPC 和 HTTP 请求共享此处理函数，实现协议无关的业务逻辑。
package handler

import (
	"context"
	"fmt"

	"%s/service/%s/internal/logic"
	"%s/service/%s/internal/svc"
)

// %sHandler 是 %s 的处理函数。
// HTTP 和 gRPC 请求共享此处理函数，消除协议差异。
//
// 参数:
//   ctx    — 请求上下文（含 request_id、trace_id 等）
//   svcCtx — 服务上下文（依赖注入容器）
//   req    — 请求参数（HTTP 时为 *http.Request 或解析后的 DTO）
//
// 返回:
//   interface{} — 响应数据（自动序列化为 JSON/Protobuf）
//   error       — 业务错误（由框架统一转换为响应格式）
func %sHandler(ctx context.Context, svcCtx *svc.ServiceContext, req interface{}) (interface{}, error) {
	// TODO: 类型断言解析请求参数
	// request, ok := req.(*dto.%sRequest)
	// if !ok {
	//     return nil, fmt.Errorf("invalid request type")
	// }
	_ = req // 抑制未使用变量警告

	l := logic.New%sLogic(ctx, svcCtx)
	return l.Execute()
}
`, handler.Name, handler.Doc, g.module, svc.Group, g.module, svc.Group,
				handler.Name, handler.Doc, handler.Name, handler.Name,
				handler.Name)

			os.WriteFile(filepath.Join(dir, handlerName+".go"), []byte(content), 0644)
		}
	}

	// 生成 routes.go — 集中注册所有路由
	g.generateRoutes(dir, svc, file)
}

// generateRoutes 生成路由注册文件。
// 将所有 handler 的路由集中注册到 HTTP mux 中。
// SSE 端点使用 sse.NewChannelHandler 注册，绕过 JSON 响应包装。
func (g *Generator) generateRoutes(dir string, svc *ast.Service, file *ast.File) {
	var registrations strings.Builder
	for _, handler := range svc.Handlers {
		if handler.IsSSE {
			// SSE 端点：直接注册 http.Handler，绕过 JSON 包装
			registrations.WriteString(fmt.Sprintf(`	// %s: %s (SSE 实时推送)
	mux.Handle("%s%s", %sSSEHandler(svcCtx))
`, handler.Doc, handler.Path, svc.Prefix, handler.Path, handler.Name))
		} else {
			registrations.WriteString(fmt.Sprintf(`	// %s: %s
	mux.HandleFunc("%s%s", %sHandlerWrapper(svcCtx))
`, handler.Doc, handler.Path, svc.Prefix, handler.Path, handler.Name))
		}
	}

	content := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// 路由注册 — 将所有 handler 注册到 HTTP mux。
package handler

import (
	"net/http"

	"%s/service/%s/internal/svc"
)

// RegisterRoutes 将所有 handler 注册到 HTTP ServeMux。
// 在 main.go 中调用此函数完成路由注册。
func RegisterRoutes(mux *http.ServeMux, svcCtx *svc.ServiceContext) {
%s}
`, g.module, svc.Group, registrations.String())

	os.WriteFile(filepath.Join(dir, "routes.go"), []byte(content), 0644)
}

// =============================================================================
// Logic 生成
// =============================================================================

// generateLogic 生成业务逻辑框架代码。
// 每个 handler 对应一个 logic 文件，包含完整的 CRUD 模板。
// SSE 端点生成流式逻辑（返回 <-chan sse.Event）。
func (g *Generator) generateLogic(dir string, svc *ast.Service) {
	for _, handler := range svc.Handlers {
		handlerName := toSnakeCase(handler.Name)

		if handler.IsSSE {
			// SSE 逻辑：生成流式事件推送
			content := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// SSE Logic: %s — 实时事件推送
// 在此文件中实现具体的事件推送逻辑。
// 返回一个事件 channel，框架自动处理 SSE 写入和心跳。
package logic

import (
	"context"
	"fmt"
	"time"

	"%s/core/sse"
	"%s/service/%s/internal/svc"
)

// %sSSELogic 是 %s 的 SSE 事件推送逻辑处理器。
// 通过 channel 发送事件，框架自动写入 SSE 响应流。
type %sSSELogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

// New%sSSELogic 创建 SSE 逻辑实例。
func New%sSSELogic(ctx context.Context, svcCtx *svc.ServiceContext) *%sSSELogic {
	return &%sSSELogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Execute 返回事件 channel。
// 在 goroutine 中持续发送事件，直到 ctx 被取消或所有事件发送完毕。
//
// 实现建议：
//   1. 监听数据源（数据库变更、消息队列、定时器）
//   2. 构造 sse.Event 并发送到 channel
//   3. 监听 ctx.Done() 及时退出
//
// 示例：
//   go func() {
//       defer close(ch)
//       ticker := time.NewTicker(5 * time.Second)
//       defer ticker.Stop()
//       for {
//           select {
//           case <-ticker.C:
//               ch <- sse.NewEvent().WithType("update").WithData(data).Build()
//           case <-l.ctx.Done():
//               return
//           }
//       }
//   }()
//   return ch
func (l *%sSSELogic) Execute() <-chan sse.Event {
	ch := make(chan sse.Event, 64)

	go func() {
		defer close(ch)

		// TODO: 实现事件推送逻辑
		// 示例：定时推送数据
		ticker := time.NewTicker(5 * time.Second)
		defer ticker.Stop()

		for {
			select {
			case <-ticker.C:
				ch <- sse.NewEvent().
					WithType("message").
					WithData(map[string]interface{}{
						"message": fmt.Sprintf("%s: event at %%v", time.Now()),
					}).
					Build()
			case <-l.ctx.Done():
				return
			}
		}
	}()

	return ch
}
`, handler.Doc, g.module, g.module, svc.Group,
				handler.Name, handler.Doc, handler.Name,
				handler.Name, handler.Name, handler.Name,
				handler.Name, handler.Doc)

			os.WriteFile(filepath.Join(dir, handlerName+"_sse.go"), []byte(content), 0644)
		} else {
			content := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// Logic: %s
// 在此文件中实现具体的业务逻辑。
// 业务逻辑应保持纯函数风格，不依赖 HTTP/gRPC 协议细节。
package logic

import (
	"context"
	"fmt"

	"%s/service/%s/internal/svc"
)

// %sLogic 是 %s 的业务逻辑处理器。
// 封装了该接口的所有业务规则和数据处理。
type %sLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

// New%sLogic 创建业务逻辑实例。
// ctx: 请求上下文（含 request_id、trace_id、user_id 等元信息）
// svcCtx: 服务上下文（提供数据库连接、缓存、配置等依赖）
func New%sLogic(ctx context.Context, svcCtx *svc.ServiceContext) *%sLogic {
	return &%sLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// Execute 执行业务逻辑。
//
// 实现建议：
//   1. 参数校验 — 使用 validator 包验证请求参数
//   2. 业务规则 — 执行领域逻辑
//   3. 数据持久化 — 通过 svcCtx 获取 DB/Cache 实例
//   4. 领域事件 — 发布事件通知其他模块
//   5. 返回结果 — 返回响应 DTO
//
// 返回:
//   interface{} — 响应数据（支持任意类型）
//   error       — 业务错误（框架自动映射 HTTP 状态码）
func (l *%sLogic) Execute() (interface{}, error) {
	// TODO: 实现业务逻辑
	
	// 示例：参数校验
	// if err := l.validate(); err != nil {
	//     return nil, err
	// }
	
	// 示例：数据库操作
	// result, err := l.svcCtx.DB.Query(...)
	
	// 示例：事件发布
	// l.svcCtx.EventBus.Publish(ctx, event.New%sCreated(...))
	
	return nil, fmt.Errorf("%s: not implemented")
}

// validate 校验请求参数（预留）。
// func (l *%sLogic) validate() error {
//     // TODO: 添加参数校验
//     return nil
// }
`, handler.Doc, g.module, svc.Group, handler.Name, handler.Doc,
				handler.Name, handler.Name, handler.Name, handler.Name,
				handler.Name, handler.Name, handler.Doc, handler.Name)

			os.WriteFile(filepath.Join(dir, handlerName+".go"), []byte(content), 0644)
		}
	}
}

// =============================================================================
// ServiceContext 生成
// =============================================================================

// generateServiceContext 生成服务上下文（依赖注入容器）。
func (g *Generator) generateServiceContext(dir string, svc *ast.Service) {
	content := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// Package svc 提供 %s 服务的依赖注入上下文。
//
// ServiceContext 是服务的依赖注入容器，所有需要注入的依赖项都定义在此结构体中。
// 包括但不限于：配置、数据库连接、缓存客户端、事件总线、RPC 客户端等。
package svc

import (
	"%s/service/%s/internal/config"
)

// ServiceContext 是 %s 服务的依赖注入上下文。
// 添加新的依赖项时，在此结构体中添加对应字段，
// 并在 NewServiceContext 中初始化。
type ServiceContext struct {
	Config *config.Config // 服务配置（从 etc/%s.yaml 加载）
	
	// TODO: 添加实际依赖项
	// DB       *sql.DB          // 数据库连接池
	// Redis    *redis.Client    // 缓存客户端
	// EventBus event.Bus        // 事件总线
	// RPCClient *rpc.Client     // RPC 客户端
}

// NewServiceContext 创建服务上下文实例。
// cfg: 服务配置（包含数据库连接串、缓存地址等）
func NewServiceContext(cfg *config.Config) *ServiceContext {
	return &ServiceContext{
		Config: cfg,
		
		// TODO: 初始化依赖项
		// DB:    initDB(cfg),
		// Redis: initRedis(cfg),
	}
}
`, svc.Name, g.module, svc.Group, svc.Name, svc.Group)

	os.WriteFile(filepath.Join(dir, "service_context.go"), []byte(content), 0644)
}

// =============================================================================
// 中间件生成
// =============================================================================

// generateMiddleware 生成自定义中间件代码。
func (g *Generator) generateMiddleware(dir string, svc *ast.Service) {
	content := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// Package middleware 提供 %s 服务的自定义中间件。
//
// 框架已提供 RequestID、Tracing、Logger、Recovery、CORS、Timeout、Metrics 内置中间件。
// 在此文件中添加服务特有的中间件，如认证、授权、审计等。
package middleware

import (
	"context"
	"fmt"

	"%s/core"
	"%s/core/middleware"
)

// AuthMiddleware 是 JWT / Token 认证中间件示例。
// 从请求头中提取 Authorization token 并验证。
//
// 使用方式（在 main.go 中）：
//   chain := middleware.DefaultChain()
//   chain.Use(middleware.AuthMiddleware())
func AuthMiddleware() core.Middleware {
	return func(next core.Handler) core.Handler {
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			// TODO: 从 context/metadata 中提取 token
			// token := GetTokenFromContext(ctx)
			// if token == "" {
			//     return nil, fmt.Errorf("unauthorized: missing token")
			// }
			//
			// // 验证 token
			// claims, err := ValidateToken(token)
			// if err != nil {
			//     return nil, fmt.Errorf("unauthorized: %%w", err)
			// }
			//
			// // 注入用户信息到 context
			// ctx = context.WithValue(ctx, UserKey, claims)

			return next(ctx, req)
		}
	}
}

// GetRequestID 从 context 中提取请求 ID（委托给框架）。
func GetRequestID(ctx context.Context) string {
	return middleware.GetRequestID(ctx)
}

// ExampleMiddleware 是一个简单的示例中间件，打印请求信息。
func ExampleMiddleware() core.Middleware {
	return func(next core.Handler) core.Handler {
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			fmt.Printf("[%%s] request: %%v\n", middleware.GetRequestID(ctx), req)
			resp, err := next(ctx, req)
			fmt.Printf("[%%s] response: %%v, err: %%v\n", middleware.GetRequestID(ctx), resp, err)
			return resp, err
		}
	}
}
`, svc.Name, g.module, g.module)

	os.WriteFile(filepath.Join(dir, "auth.go"), []byte(content), 0644)
}

// =============================================================================
// 客户端 SDK 生成
// =============================================================================

// generateClient 生成客户端 SDK。
func (g *Generator) generateClient(dir string, svc *ast.Service) {
	var methods strings.Builder
	for _, handler := range svc.Handlers {
		methods.WriteString(fmt.Sprintf(`// %s 调用 %s 接口。
// ctx: 请求上下文（可携带超时、trace_id 等）
// req: 请求参数（对应 API 的请求体）
// 返回: 响应数据 和 可能的错误
func (c *Client) %s(ctx context.Context, req interface{}) (interface{}, error) {
	return c.call(ctx, "%s", req)
}
`, handler.Name, handler.Doc, handler.Name, handler.Name))
	}

	content := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// Package client 提供 %s 服务的 HTTP 客户端 SDK。
//
// 使用方式：
//   client := client.NewClient("http://localhost:8080")
//   resp, err := client.CreateUser(ctx, &CreateUserReq{...})
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"%s/core/response"
)

// Client 是 %s 服务的 HTTP 客户端。
// 封装了连接管理、序列化和错误处理。
type Client struct {
	serviceName string       // 服务名称
	baseURL     string       // 服务基础 URL
	httpClient  *http.Client // HTTP 客户端实例
}

// NewClient 创建客户端实例。
// baseURL: 服务的 HTTP 地址（如 "http://localhost:8080"）
func NewClient(baseURL string) *Client {
	return &Client{
		serviceName: "%s",
		baseURL:     baseURL,
		httpClient: &http.Client{
			Timeout: 30 * time.Second,
		},
	}
}

// call 执行 RPC 调用。
// method: API 路径（如 "/api/v1/users"）
// req: 请求体（将序列化为 JSON）
func (c *Client) call(ctx context.Context, method string, req interface{}) (interface{}, error) {
	// 序列化请求体
	body, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("client: marshal error: %%w", err)
	}

	// 构建 HTTP 请求
	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, c.baseURL+method, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("client: create request error: %%w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	// 发送请求
	httpResp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("client: request error: %%w", err)
	}
	defer httpResp.Body.Close()

	// 读取响应
	respBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return nil, fmt.Errorf("client: read response error: %%w", err)
	}

	// 解析统一响应格式
	var resp response.Response
	if err := json.Unmarshal(respBody, &resp); err != nil {
		return nil, fmt.Errorf("client: unmarshal response error: %%w", err)
	}

	if resp.Code != 0 {
		return nil, fmt.Errorf("client: api error [%%d]: %%s", resp.Code, resp.Msg)
	}

	return resp.Data, nil
}

%s
`, svc.Name, g.module, svc.Name, svc.Group, methods.String())

	os.WriteFile(filepath.Join(dir, "http_client.go"), []byte(content), 0644)
}

// =============================================================================
// OpenAPI 文档生成
// =============================================================================

// generateOpenAPI 生成 OpenAPI v3 文档。
func (g *Generator) generateOpenAPI(dir string, svc *ast.Service, file *ast.File) {
	content := fmt.Sprintf(`# OpenAPI v3.0 — %s
# 由 Nexus Micro 自动生成
# 此文件描述服务的所有 API 端点，可供 Swagger UI、Postman 等工具导入。

openapi: "3.0.0"
info:
  title: %s
  description: %s
  version: %s
  contact:
    name: Nexus Micro Team
servers:
  - url: http://localhost:8080%s
    description: Development server
  - url: https://api.example.com%s
    description: Production server
paths:
`, svc.Name, svc.Name, file.Info.Desc, file.Info.Version, svc.Prefix, svc.Prefix)

	for _, handler := range svc.Handlers {
		content += fmt.Sprintf(`  %s:
    %s:
      summary: %s
      description: %s
      operationId: %s
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/%sResponse'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
`,
			handler.Path, strings.ToLower(handler.Method), handler.Doc, handler.Doc,
			handler.Name, handler.Name)
	}

	content += `components:
  schemas:
    Response:
      type: object
      properties:
        code:
          type: integer
          description: 业务状态码（0 表示成功）
        msg:
          type: string
          description: 提示信息
        data:
          type: object
          description: 响应数据
        request_id:
          type: string
          description: 请求追踪 ID
`

	os.WriteFile(filepath.Join(dir, "openapi.yaml"), []byte(content), 0644)
}

// =============================================================================
// Server 生成
// =============================================================================

// generateServer 生成 HTTP/gRPC 服务器路由注册代码。
func (g *Generator) generateServer(dir string, svc *ast.Service, file *ast.File) {
	httpContent := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// HTTP 服务器路由注册。
//
// 将 handler 包中定义的处理函数注册到 HTTP ServeMux 中。
// 使用 handler.WrapHandler 包装，自动处理请求解析、响应序列化和错误转换。
// SSE 端点直接注册http.Handler，绕过 JSON 响应包装。
package server

import (
	"net/http"

	"%s/core/response"
	"%s/service/%s/internal/handler"
	"%s/service/%s/internal/svc"
)

// RegisterHTTPRoutes 注册 HTTP 路由。
// mux: HTTP ServeMux 实例
// svcCtx: 服务上下文（依赖注入容器）
//
// 使用方式（在 main.go 中）：
//   mux := http.NewServeMux()
//   server.RegisterHTTPRoutes(mux, svcCtx)
func RegisterHTTPRoutes(mux *http.ServeMux, svcCtx *svc.ServiceContext) {
	// 使用 handler 包中自动生成的路由注册
	handler.RegisterRoutes(mux, svcCtx)
`, g.module, g.module, svc.Group, g.module, svc.Group)

	// 为每个 handler 生成 Wrapper 函数
	for _, handler := range svc.Handlers {
		if handler.IsSSE {
			httpContent += fmt.Sprintf(`
	// %sSSEHandler — SSE 端点（绕过 JSON 包装，直接推送事件流）
	mux.Handle("%s%s", handler.%sSSEHandler(svcCtx))
`, handler.Name, svc.Prefix, handler.Path, handler.Name)
		} else {
			httpContent += fmt.Sprintf(`
	// %sHandlerWrapper 包装 %s 处理函数，自动处理 HTTP 请求/响应转换。
	mux.HandleFunc("%s%s", func(w http.ResponseWriter, r *http.Request) {
		handler.WrapHandler(func(ctx, req) (data, err) {
			return handler.%sHandler(ctx, svcCtx, req)
		}).ServeHTTP(w, r)
	})
`, handler.Name, handler.Doc, svc.Prefix, handler.Path, handler.Name)
		}
	}

	httpContent += "}\n"
	os.WriteFile(filepath.Join(dir, "http.go"), []byte(httpContent), 0644)

	// gRPC 路由注册
	grpcContent := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// gRPC 服务器路由注册。
package server

// RegisterGRPCRoutes 注册 gRPC 路由（预留）。
// 后续版本将集成 protoc-gen-go-grpc 生成的代码。
func RegisterGRPCRoutes() {
	// TODO: 实现 gRPC 服务注册
	// pb.Register%sServer(grpcServer, &%sServer{})
}
`, svc.Name, svc.Name)
	os.WriteFile(filepath.Join(dir, "grpc.go"), []byte(grpcContent), 0644)
}

// =============================================================================
// Main 入口生成
// =============================================================================

// generateMain 生成 main.go 入口文件。
// 包含完整的中间件链、路由注册、治理组件和优雅关闭。
func (g *Generator) generateMain(dir string, svc *ast.Service, file *ast.File) {
	content := fmt.Sprintf(`// Code generated by Nexus Micro. DO NOT EDIT.
// %s 服务入口。
//
// 启动流程：
//   1. 加载配置（etc/%s.yaml）
//   2. 初始化依赖注入容器（ServiceContext）
//   3. 构建中间件链（SSE → RequestID → Tracing → Logger → Recovery → CORS → Timeout → Metrics）
//   4. 注册 HTTP 路由
//   5. 启动 HTTP 服务器（含健康检查端点）
//   6. 优雅关闭（捕获 SIGINT/SIGTERM 信号）
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"%s/core/middleware"
	"%s/core/response"
	"%s/core/server"
	"%s/service/%s/internal/config"
	"%s/service/%s/internal/handler"
	"%s/service/%s/internal/server"
	"%s/service/%s/internal/svc"
)

func main() {
	// 1. 创建服务器实例（加载配置、初始化中间件链）
	srv := server.New(
		server.WithName("%s"),
		server.WithConfig("etc/%s.yaml"),
	)

	// 2. 初始化服务上下文（依赖注入容器）
	cfg := config.NewConfig(srv.Config())
	svcCtx := svc.NewServiceContext(cfg)

	// 3. 创建 HTTP 路由并注册业务路由
	mux := http.NewServeMux()

	// 框架内置端点
	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		response.Success(map[string]interface{}{
			"status":  "ok",
			"service": "%s",
			"version": "%s",
			"time":    time.Now().Format(time.RFC3339),
		}).WithRequestID(middleware.GetRequestID(r.Context())).WriteTo(w)
	})

	mux.HandleFunc("/ready", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		fmt.Fprintf(w, "ready")
	})

	mux.HandleFunc("/live", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		fmt.Fprintf(w, "alive")
	})

	// 注册业务路由（由代码生成器自动生成）
	server.RegisterHTTPRoutes(mux, svcCtx)

	// 4. 将 mux 注册到框架服务器
	srv.RegisterService(mux)

	// 5. 启动服务器（带优雅关闭）
	log.Printf("[%s] starting on :%%d", srv.Name(), cfg.Server.HTTP.Port)
	if err := srv.Start(); err != nil {
		log.Fatalf("[%s] server error: %%v", srv.Name(), err)
	}
}

// 优雅关闭处理（备用，框架 server 已内置）
func init() {
	go func() {
		quit := make(chan os.Signal, 1)
		signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
		<-quit
		log.Println("[shutdown] received signal, waiting for graceful stop...")
	}()
}
`, svc.Doc, svc.Group, g.module, g.module, g.module,
		g.module, svc.Group, g.module, svc.Group, g.module, svc.Group,
		g.module, svc.Group, svc.Group, svc.Group,
		svc.Group, file.Info.Version, svc.Group, svc.Group)

	os.WriteFile(filepath.Join(dir, "main.go"), []byte(content), 0644)
}

// =============================================================================
// Proto 生成
// =============================================================================

// generateProto 生成 Protobuf 定义文件。
func (g *Generator) generateProto(dir string, svc *ast.Service, file *ast.File) {
	content := fmt.Sprintf(`// %s.proto — 由 Nexus Micro 自动生成
// 此文件定义了 %s 服务的 gRPC 接口和消息类型。
syntax = "proto3";

package %s;

option go_package = "%s/service/%s";

// %s 服务定义
service %s {
`, svc.Group, svc.Name, svc.Group, g.module, svc.Group, svc.Name, svc.Name)

	for _, handler := range svc.Handlers {
		if handler.HasGRPC {
			content += fmt.Sprintf(`  // %s
  rpc %s(%sReq) returns (%sResp);
`, handler.Doc, handler.Name, handler.Name, handler.Name)
		}
	}

	content += "}\n\n"

	// 生成消息定义
	for _, t := range file.Types {
		content += fmt.Sprintf("// %s\n", t.Name)
		content += fmt.Sprintf("message %s {\n", t.Name)
		for i, field := range t.Fields {
			protoType := goTypeToProto(field.Type)
			content += fmt.Sprintf("  %s %s = %d; // %s\n", protoType, strings.ToLower(field.Name), i+1, field.Name)
		}
		content += "}\n\n"
	}

	os.WriteFile(filepath.Join(dir, svc.Group+".proto"), []byte(content), 0644)
}

// =============================================================================
// YAML 配置生成
// =============================================================================

// generateServiceYAML 生成服务的默认 YAML 配置文件。
func (g *Generator) generateServiceYAML(dir string, svc *ast.Service) {
	etcDir := filepath.Join(dir, "etc")
	os.MkdirAll(etcDir, 0755)

	content := fmt.Sprintf(`# %s 服务配置
# 由 nx gen api 自动生成，可根据需要修改。

# ---------------------------------------------------------------------------
# 服务器配置
# ---------------------------------------------------------------------------
server:
  name: %s                 # 服务名称（用于注册中心和日志）
  http:
    port: 8080            # HTTP 监听端口
  grpc:
    port: 9090            # gRPC 监听端口

# ---------------------------------------------------------------------------
# 服务治理配置
# ---------------------------------------------------------------------------
governance:
  ratelimit:
    rate: 1000            # 每秒请求数
    burst: 2000           # 突发请求数
  circuitbreaker:
    window_size: 10s      # 统计窗口
    bucket_count: 10      # 窗口桶数
    min_requests: 20      # 最小请求数（低于此值不触发熔断）
    error_rate: 0.5       # 错误率阈值
    sleep_window: 30s     # 熔断后休眠时间
  shedding:
    cpu_threshold: 0.9    # CPU 使用率阈值
    mem_threshold: 0.85   # 内存使用率阈值
  timeout: 30s            # 请求超时时间

# ---------------------------------------------------------------------------
# 中间件配置
# ---------------------------------------------------------------------------
middleware:
  cors: true              # 跨域支持
  request_id: true        # 请求 ID 生成
  tracing: true           # 链路追踪
  logger: true            # 请求日志
  recovery: true          # Panic 恢复
  metrics: true           # 指标采集

# ---------------------------------------------------------------------------
# 注册中心配置
# ---------------------------------------------------------------------------
registry:
  provider: static        # static | etcd | consul | k8s
  static_endpoints:
    - localhost:8080
  etcd_endpoints:
    - localhost:2379
  consul_addr: localhost:8500

# ---------------------------------------------------------------------------
# 日志配置
# ---------------------------------------------------------------------------
log:
  level: info             # debug | info | warn | error
  format: json            # json | text
`, svc.Doc, svc.Group)

	os.WriteFile(filepath.Join(etcDir, svc.Group+".yaml"), []byte(content), 0644)
}

// =============================================================================
// 客户端 SDK 代码生成（nx gen client）
// =============================================================================

// GenerateClient 为指定服务名生成客户端 SDK。
// serviceName: 目标服务名（如 "user"）
func (g *Generator) GenerateClient(serviceName string) error {
	clientDir := filepath.Join(g.outputDir, serviceName+"-client")
	if err := os.MkdirAll(clientDir, 0755); err != nil {
		return fmt.Errorf("generator: cannot create client dir: %w", err)
	}

	content := fmt.Sprintf(`// Package client 提供 %s 服务的调用客户端 SDK。
// 封装了 HTTP 调用、统一响应解析和错误处理。
//
// 使用方式：
//   client := client.NewClient("http://localhost:8080")
//   resp, err := client.Call(ctx, "/api/v1/users", req)
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"%s/core/response"
)

// Client 是 %s 服务的 HTTP 客户端。
type Client struct {
	baseURL    string       // 服务地址
	httpClient *http.Client // HTTP 客户端
}

// NewClient 创建客户端实例。
// baseURL: 服务 HTTP 地址（如 "http://localhost:8080"）
func NewClient(baseURL string) *Client {
	return &Client{
		baseURL: baseURL,
		httpClient: &http.Client{
			Timeout: 30 * time.Second,
		},
	}
}

// Call 调用远程 API。
// ctx:  请求上下文（支持超时和取消）
// path: API 路径（如 "/api/v1/users"）
// req:  请求参数（将序列化为 JSON）
func (c *Client) Call(ctx context.Context, path string, req interface{}) (interface{}, error) {
	body, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("client: marshal error: %%w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, c.baseURL+path, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("client: create request error: %%w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("client: request error: %%w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("client: read response error: %%w", err)
	}

	var apiResp response.Response
	if err := json.Unmarshal(respBody, &apiResp); err != nil {
		return nil, fmt.Errorf("client: unmarshal response error: %%w", err)
	}

	if apiResp.Code != 0 {
		return nil, fmt.Errorf("client: api error [%%d]: %%s", apiResp.Code, apiResp.Msg)
	}

	return apiResp.Data, nil
}

// Get 发送 GET 请求。
func (c *Client) Get(ctx context.Context, path string) (interface{}, error) {
	httpReq, err := http.NewRequestWithContext(ctx, http.MethodGet, c.baseURL+path, nil)
	if err != nil {
		return nil, fmt.Errorf("client: create request error: %%w", err)
	}

	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("client: request error: %%w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("client: read response error: %%w", err)
	}

	var apiResp response.Response
	if err := json.Unmarshal(respBody, &apiResp); err != nil {
		return nil, fmt.Errorf("client: unmarshal response error: %%w", err)
	}

	if apiResp.Code != 0 {
		return nil, fmt.Errorf("client: api error [%%d]: %%s", apiResp.Code, apiResp.Msg)
	}

	return apiResp.Data, nil
}
`, serviceName, g.module, serviceName)

	os.WriteFile(filepath.Join(clientDir, "client.go"), []byte(content), 0644)

	// 生成 README
	readme := fmt.Sprintf(`# %s Client SDK

自动生成的 %s 服务客户端 SDK。

## 使用方式

`+"```go"+`
package main

import (
    "context"
    "fmt"
    "%s-client"
)

func main() {
    c := client.NewClient("http://localhost:8080")
    
    ctx := context.Background()
    resp, err := c.Call(ctx, "/api/v1/users/create", map[string]interface{}{
        "name": "test",
    })
    if err != nil {
        panic(err)
    }
    fmt.Println(resp)
}
`+"```"+`
`, serviceName, serviceName, serviceName)

	os.WriteFile(filepath.Join(clientDir, "README.md"), []byte(readme), 0644)

	return nil
}
