apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
  labels:
    app.kubernetes.io/name: nexus-service
spec:
  type: ClusterIP
  selector:
    app: nexus-service
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 9090
    targetPort: grpc
    protocol: TCP
