// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.34.0
// source: home.proto

package homepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Banner 横幅
type Banner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Sort          int32                  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Banner) Reset() {
	*x = Banner{}
	mi := &file_home_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_home_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_home_proto_rawDescGZIP(), []int{0}
}

func (x *Banner) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Banner) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Banner) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Banner) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Banner) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

// 获取首页
type GetHomeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHomeReq) Reset() {
	*x = GetHomeReq{}
	mi := &file_home_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHomeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHomeReq) ProtoMessage() {}

func (x *GetHomeReq) ProtoReflect() protoreflect.Message {
	mi := &file_home_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHomeReq.ProtoReflect.Descriptor instead.
func (*GetHomeReq) Descriptor() ([]byte, []int) {
	return file_home_proto_rawDescGZIP(), []int{1}
}

type GetHomeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banners       []*Banner              `protobuf:"bytes,1,rep,name=banners,proto3" json:"banners,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHomeResp) Reset() {
	*x = GetHomeResp{}
	mi := &file_home_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHomeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHomeResp) ProtoMessage() {}

func (x *GetHomeResp) ProtoReflect() protoreflect.Message {
	mi := &file_home_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHomeResp.ProtoReflect.Descriptor instead.
func (*GetHomeResp) Descriptor() ([]byte, []int) {
	return file_home_proto_rawDescGZIP(), []int{2}
}

func (x *GetHomeResp) GetBanners() []*Banner {
	if x != nil {
		return x.Banners
	}
	return nil
}

func (x *GetHomeResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_home_proto protoreflect.FileDescriptor

const file_home_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"home.proto\x12\x04home\"j\n" +
	"\x06Banner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\x05R\x04sort\"\f\n" +
	"\n" +
	"GetHomeReq\"O\n" +
	"\vGetHomeResp\x12&\n" +
	"\abanners\x18\x01 \x03(\v2\f.home.BannerR\abanners\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2=\n" +
	"\vHomeService\x12.\n" +
	"\aGetHome\x12\x10.home.GetHomeReq\x1a\x11.home.GetHomeRespBGZEgithub.com/xyxuliang/nexus-micro/examples/rpc-demo/pkg/pb/home;homepbb\x06proto3"

var (
	file_home_proto_rawDescOnce sync.Once
	file_home_proto_rawDescData []byte
)

func file_home_proto_rawDescGZIP() []byte {
	file_home_proto_rawDescOnce.Do(func() {
		file_home_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_home_proto_rawDesc), len(file_home_proto_rawDesc)))
	})
	return file_home_proto_rawDescData
}

var file_home_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_home_proto_goTypes = []any{
	(*Banner)(nil),      // 0: home.Banner
	(*GetHomeReq)(nil),  // 1: home.GetHomeReq
	(*GetHomeResp)(nil), // 2: home.GetHomeResp
}
var file_home_proto_depIdxs = []int32{
	0, // 0: home.GetHomeResp.banners:type_name -> home.Banner
	1, // 1: home.HomeService.GetHome:input_type -> home.GetHomeReq
	2, // 2: home.HomeService.GetHome:output_type -> home.GetHomeResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_home_proto_init() }
func file_home_proto_init() {
	if File_home_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_home_proto_rawDesc), len(file_home_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_home_proto_goTypes,
		DependencyIndexes: file_home_proto_depIdxs,
		MessageInfos:      file_home_proto_msgTypes,
	}.Build()
	File_home_proto = out.File
	file_home_proto_goTypes = nil
	file_home_proto_depIdxs = nil
}
